config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/articles", to: "articles#index"

  get '/oauth2-callback', to: 'o_auth#oauth_callback'
  get '/logout', to: 'o_auth#logout'
  get '/login', to: 'o_auth#login'
  get '/register', to: 'o_auth#register'
  get '/endsession', to: 'o_auth#endsession'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def require_login
    puts "checking login"
    puts session[:user_jwt]
    unless session[:user_jwt]
      redirect_to login_url # halts request cycle
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def index
  end
end

app/controllers/o_auth_controller.rb
class OAuthController < ApplicationController

  skip_before_action :require_login

  def initialize
    @oauth_client = OAuth2::Client.new(Rails.configuration.x.oauth.client_id,
                                       Rails.configuration.x.oauth.client_secret,
                                       authorize_url: '/oauth2/authorize',
                                       site: Rails.configuration.x.oauth.idp_url,
                                       token_url: '/oauth2/token',
                                       redirect_uri: Rails.configuration.x.oauth.redirect_uri)
  end

  # The OAuth callback
  def oauth_callback
    # Make a call to exchange the authorization_code for an access_token
    response = @oauth_client.auth_code.get_token(params[:code])

    # Extract the access token from the response
    token = response.to_hash[:access_token]

    # Decode the token
    begin
      decoded = TokenDecoder.new(token, @oauth_client.id).decode
    rescue Exception => error
      puts "An unexpected exception occurred: #{error.inspect}"
      head :forbidden
      return
    end

    # Set the token on the user session
    session[:user_jwt] = {value: decoded, httponly: true}

    redirect_to articles_path
  end

  # will be called by FusionAuth
  def endsession

    # Reset Rails session
    reset_session

    redirect_to root_path
  end

  def logout
     
    redirect_to Rails.configuration.x.oauth.idp_url + "/oauth2/logout?client_id=" + Rails.configuration.x.oauth.client_id, allow_other_host: true 

  end

  def login
    redirect_to @oauth_client.auth_code.authorize_url, allow_other_host: true 
  end

  def register
    redirect_to @oauth_client.auth_code.authorize_url.gsub!('authorize','register'), allow_other_host: true 
  end
end

app/controllers/oauth_controller.rb
class OAuthController < ApplicationController
  def initialize
    @oauth_client = OAuth2::Client.new(Rails.configuration.x.oauth.client_id,
                                       Rails.configuration.x.oauth.client_secret,
                                       authorize_url: '/oauth2/authorize',
                                       site: Rails.configuration.x.oauth.idp_url,
                                       token_url: '/oauth2/token',
                                       redirect_uri: Rails.configuration.x.oauth.redirect_uri)
  end

  # The OAuth callback
  def oauth_callback
    # Make a call to exchange the authorization_code for an access_token
    response = @oauth_client.auth_code.get_token(params[:code])

    # Extract the access token from the response
    token = response.to_hash[:access_token]

    # Decode the token
    begin
      decoded = TokenDecoder.new(token, @oauth_client.id).decode
    rescue Exception => error
      "An unexpected exception occurred: #{error.inspect}"
      head :forbidden
      return
    end

    # Set the token on the user session
    session[:user_jwt] = {value: decoded, httponly: true}

    redirect_to root_path
  end

  def logout
    # Invalidate session with FusionAuth
    @oauth_client.request(:get, 'oauth2/logout')

    # Reset Rails session
    reset_session

    redirect_to root_path
  end

  def login
    redirect_to @oauth_client.auth_code.authorize_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h4>Protected content</h4>
<p>
Here's a list of protected content.
</p>

app/views/home/index.html.erb
<h4>Welcome to the FusionAuth DEMO application</h4>
<p>
<% if session[:user_jwt].nil? %>
Please <%= link_to "register", register_path %> or <%= link_to "login", login_path %>. 
<% else %>
Please <%= link_to "logout", logout_path %>.
<% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Confapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<body class="app-sidebar-closed">
<main>
  <header class="app-header">
    <div class="right-menu">
      <nav>
        <ul>
            <li class="help"><a target="_blank" href="https://fusionauth.io/docs/"><i class="fa fa-question-circle-o"></i> Help</a></li>
        </ul>
      </nav>
    </div>
  </header>


<main class="page-body container">
  <div class="row center">
    <div class="col-xs-12 col-sm-12 col-md-10 col-lg-8">
<div class="panel">
<p>
<% if session[:user_jwt].nil? %>
<%= link_to "register", register_path %> | <%= link_to "login", login_path %>
<% else %>
<%= link_to "logout", logout_path %>
<% end %>
</div>

<div class="panel">
  <main>
<%= yield %>
  </main>
</div>
</div>
</div>

<div class="row center">
  <div class="col-xs-6 col-sm-6 col-md-5 col-lg-4">
<!-- I don't know why we need this, but if it goes away everything gets small -->
  </div>
</div>

</main>

</html>